--Insert users
INSERT INTO USER("NAME") VALUES ('Abdullah');
INSERT INTO USER("NAME") VALUES ('Arpit');
INSERT INTO USER("NAME") VALUES ('Aamir');

--Insert bank accounts
INSERT INTO BANKACCOUNT("ACCOUNTNUMBER", "BALANCE") VALUES (123123123, 10000);
INSERT INTO BANKACCOUNT("ACCOUNTNUMBER", "BALANCE") VALUES (123123124, 20000);
INSERT INTO BANKACCOUNT("ACCOUNTNUMBER", "BALANCE") VALUES (123123125, 30000);

--Insert user bank accounts
INSERT INTO USERBANKACCOUNT("BANKACCOUNT_ID", "USER_ID") VALUES (1, 1);
INSERT INTO USERBANKACCOUNT("BANKACCOUNT_ID", "USER_ID") VALUES (1, 2);

INSERT INTO USERBANKACCOUNT("BANKACCOUNT_ID", "USER_ID") VALUES (2, 3);
INSERT INTO USERBANKACCOUNT("BANKACCOUNT_ID", "USER_ID") VALUES (2, 2);

INSERT INTO USERBANKACCOUNT("BANKACCOUNT_ID", "USER_ID") VALUES (3, 3);
INSERT INTO USERBANKACCOUNT("BANKACCOUNT_ID", "USER_ID") VALUES (3, 2);
INSERT INTO USERBANKACCOUNT("BANKACCOUNT_ID", "USER_ID") VALUES (3, 1);


